- hosts: all
  become: yes
  tasks:
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: latest

    - name: Clone application repository
      git:
        repo: 'https://github.com/azayyad48/DevOps-Stage-4.git'
        dest: /home/ubuntu/app
        version: main

    - name: Start application
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/app
